FROM node:8.15.0-jessie

RUN mkdir -p /usr/client
WORKDIR /usr/client
COPY et-crm-client /usr/client

RUN npm cache verify
RUN npm install

EXPOSE 8080
EXPOSE 4200

CMD ["npm", "run", "start:docker"]
